### ISSUE TITLE
Tracker issue for pixel data encoding & decoding

### ISSUE THREAD

**Issue by Enet4** [Enet4/dicom-rs#125]
This will serve to keep track of issues related with the `dicom-pixeldata` crate and functionalities around it.

- [ ] Support for the photometric interpretation `MONOCHROME1` #118
- [ ] Support for the photometric interpretation `RGB` #119
- [ ] Support for the photometric interpretation `PALETTE COLOR` (not used as much as the other ones, lesser priority). #124
- Extend the API
   - [ ] Selective application of Modality and VOI LUT functions #122
      - `to_dynamic_image` only performs the Modality LUT
      - `to_ndarray` does no LUT processing
   - [ ] Support for multi-frame images. #123
- [ ] Integration with the `encoding` crate's `TransferSyntax` system. #120
- [ ] Independency from GDCM. #121
